pull_request_rules:

- name: master branch
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
    delete_head_branch: {}
  conditions:
    - base=master
    - -merged
    - -closed
    - label!=no-mergify
    - status-success=continuous-integration/drone/pr
    - '#approved-reviews-by>=1'
- name: master branch forced
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
    delete_head_branch: {}
  conditions:
    - base=master
    - -merged
    - -closed
    - label!=no-mergify
    - label=Merge Now

