pull_request_rules:

- name: merge action
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
    delete_head_branch: {}
  conditions:
    - label!=no-mergify
    - label=Merge Now
