pull_request_rules:
- name: metworkbot automerge
  actions:
    label:
      add:
        - Merge Now
  conditions:
    - author=metworkbot
    - -merged
    - -closed

- name: merge action
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
    delete_head_branch: {}
    label:
      remove:
        - Merge Now
  conditions:
    - label!=no-mergify
    - label=Merge Now
